// Generated by CodiumAI
import { render, screen, within } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import Page from "../app/page";

describe("homepage", () => {
  it("should render heading with text 'homepage'", () => {
    render(<Page />);
    const title = within(screen.getByRole("heading"));
    const text = within(title.getByText("homepage"));
    expect(text).toBeDefined();
  });
});
